FROM python:3.8
WORKDIR /star-burger/
RUN mkdir -p /var/www/static/
RUN mkdir -p /var/www/media/
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY manage.py .
COPY foodcartapp/ ./foodcartapp
COPY locations/ ./locations
COPY restaurateur/ ./restaurateur
COPY star_burger/ ./star_burger
COPY templates/ ./templates
COPY assets/ ./assets
COPY scripts/ ./scripts
RUN python manage.py collectstatic --noinput
CMD ["sh", "-c", "./scripts/start.sh \"$COMMAND\""]
