# Generated by Django 3.2.15 on 2023-03-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'элемент заказ', 'verbose_name_plural': 'элементы заказа'},
        ),
    ]
