version: "3"
services:

  frontend:

    # Сборка образа на месте
    # build:
    #   dockerfile: ../frontend/Dockerfile

    # Использование локального образа
    # image: star-burger_frontend

    # Использование удалённого образа
    image: jmuriki/star-burger_frontend

    volumes:
      - star-burger_frontend:/var/www/frontend

  backend:

    # Сборка образа на месте
    # build:
    #   dockerfile: ../backend/Dockerfile

    # Использование локального образа
    # image: star-burger_backend

    # Использование удалённого образа
    image: jmuriki/star-burger_backend

    volumes:
      - star-burger_frontend:/var/www/frontend
      - ../backend/media:/var/www/media
      - ../backend:/star-burger
    ports:
      - "11111:8000"
    environment:
      - COMMAND=runserver
    env_file:
      - ../backend/.env
    depends_on:
      - frontend

volumes:
  star-burger_frontend:
