# Generated by Django 3.2.15 on 2023-03-07 05:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20230307_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последнее обновление'),
        ),
    ]
