# Generated by Django 3.2.15 on 2023-03-01 02:49

from django.db import migrations


def add_price_to_old_orders(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.prefetch_related('product').iterator():
        if not item.price:
            item.price = item.product.price
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230228_1444'),
    ]

    operations = [
        migrations.RunPython(add_price_to_old_orders),
    ]
