# Generated by Django 3.2.15 on 2023-03-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230302_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CH', 'Наличные'), (' NC', 'Безнал')], db_index=True, default=' NC', max_length=10, verbose_name='способ оплаты'),
        ),
    ]
