# Generated by Django 3.2.15 on 2023-03-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('MR', 'Согласование'), ('RT', 'Готовится'), ('CR', 'В пути'), ('CT', 'Доставлен')], db_index=True, default='MR', max_length=10, verbose_name='статус'),
        ),
    ]
