# Generated by Django 3.2.15 on 2023-03-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230307_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='комментарий к заказу'),
        ),
    ]
